---
version: '2'
services:
  web:
    build: "."
    volumes:
    - ".:/app"
    - gemdir:/gemdir
    command: sh /app/bin/docker/dockup
    ports:
    - 3000:3000
    depends_on:
    - db
  db:
    image: postgres
    volumes:
    - "./.volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data"
volumes:
  gemdir: 
