default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password:
  host: db

development:
  <<: *default
  database: chat-hub_development

test:
  <<: *default
  database: chat-hub_test

staging:
  <<: *default
  database: chat-hub_staging
