# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b90292ac19d60f51137c173b65d09fab386004eb2c5586448f20665bbfe9b070685019fb596bcb86950944bb7eeb8d37ca5de542b8cf8852ab79ca79af38f20

test:
  secret_key_base: 5b880e45a2d78f36a0ac7d80d21604804b5cf1cdccff076af13542b6bc3071cd3d69f25666df9a7981c70c89c33079c8718e01f0cf32c1244db912aa43e43281

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
